name = "daily-content-updater"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2023-05-18"

[triggers]
crons = ["0 0 * * *"]

[build]
command = ""
[build.upload]
format = "service-worker"